export const calls = [
  {
    client: 'Org Z',
    callReason: 'Bug visual',
    status: 'Encaminhado',
    priority: 'Baixa',
    responsible: 'Carlos Lima',
    category: 'Auditoria',
    description: 'Necessário ajustar dados cadastrais.',
  },
  {
    client: 'Grupo Y',
    callReason: 'Atualização de dados',
    status: 'Concluído',
    priority: 'Média',
    responsible: 'João Silva',
    category: 'Atendimento',
    description: 'Dúvida sobre novo plano contratado.',
  },
  {
    client: 'Empresa A',
    callReason: 'Cobrança indevida',
    status: 'Concluído',
    priority: 'Alta',
    responsible: 'Beatriz Martins',
    category: 'Auditoria',
    description: 'Reclamação sobre valor divergente na fatura.',
  },
  {
    client: 'Empresa C',
    callReason: 'Erro no sistema',
    status: 'Concluído',
    priority: 'Alta',
    responsible: 'Maria Souza',
    category: 'Atendimento',
    description: 'Reclamação sobre valor divergente na fatura.',
  },
  {
    client: 'Empresa B',
    callReason: 'Erro no sistema',
    status: 'Aberto',
    priority: 'Baixa',
    responsible: 'Carlos Lima',
    category: 'Financeiro',
    description: 'Solicitação de suporte técnico urgente.',
  },
  {
    client: 'Cliente X',
    callReason: 'Solicitação de acesso',
    status: 'Encaminhado',
    priority: 'Baixa',
    responsible: 'Maria Souza',
    category: 'Financeiro',
    description: 'Cliente relatou erro ao acessar o painel.',
  },
  {
    client: 'Empresa A',
    callReason: 'Solicitação de acesso',
    status: 'Encaminhado',
    priority: 'Baixa',
    responsible: 'Maria Souza',
    category: 'Financeiro',
    description: 'Erro no envio de relatórios mensais.',
  },
  {
    client: 'Empresa C',
    callReason: 'Atualização de dados',
    status: 'Aberto',
    priority: 'Baixa',
    responsible: 'Maria Souza',
    category: 'Diretoria',
    description: 'Dúvida sobre novo plano contratado.',
  },
  {
    client: 'Empresa C',
    callReason: 'Erro no sistema',
    status: 'Concluído',
    priority: 'Alta',
    responsible: 'Carlos Lima',
    category: 'Financeiro',
    description: 'Solicitação de suporte técnico urgente.',
  },
  {
    client: 'Empresa A',
    callReason: 'Erro no sistema',
    status: 'Encaminhado',
    priority: 'Alta',
    responsible: 'Carlos Lima',
    category: 'SAC',
    description: 'Reclamação sobre valor divergente na fatura.',
  },
  {
    client: 'Cliente X',
    callReason: 'Cobrança indevida',
    status: 'Aberto',
    priority: 'Baixa',
    responsible: 'Maria Souza',
    category: 'SAC',
    description: 'Cliente relatou erro ao acessar o painel.',
  },
  {
    client: 'Empresa C',
    callReason: 'Solicitação de acesso',
    status: 'Encaminhado',
    priority: 'Média',
    responsible: 'João Silva',
    category: 'Auditoria',
    description: 'Reclamação sobre valor divergente na fatura.',
  },
  {
    client: 'Empresa B',
    callReason: 'Atualização de dados',
    status: 'Pendente',
    priority: 'Média',
    responsible: 'Beatriz Martins',
    category: 'Financeiro',
    description: 'Reclamação sobre valor divergente na fatura.',
  },
  {
    client: 'Org Z',
    callReason: 'Atualização de dados',
    status: 'Concluído',
    priority: 'Média',
    responsible: 'Rafael Costa',
    category: 'Auditoria',
    description: 'Dúvida sobre novo plano contratado.',
  },
  {
    client: 'Grupo Y',
    callReason: 'Falha de login',
    status: 'Concluído',
    priority: 'Média',
    responsible: 'Carlos Lima',
    category: 'Atendimento',
    description: 'Necessário ajustar dados cadastrais.',
  },
  {
    client: 'Empresa A',
    callReason: 'Erro no sistema',
    status: 'Encaminhado',
    priority: 'Alta',
    responsible: 'Beatriz Martins',
    category: 'Diretoria',
    description: 'Solicitação de suporte técnico urgente.',
  },
  {
    client: 'Grupo Y',
    callReason: 'Erro no sistema',
    status: 'Encaminhado',
    priority: 'Alta',
    responsible: 'Ana Paula',
    category: 'Financeiro',
    description: 'Necessário ajustar dados cadastrais.',
  },
  {
    client: 'Empresa B',
    callReason: 'Solicitação de acesso',
    status: 'Concluído',
    priority: 'Alta',
    responsible: 'Rafael Costa',
    category: 'SAC',
    description: 'Erro no envio de relatórios mensais.',
  },
  {
    client: 'Cliente X',
    callReason: 'Erro no sistema',
    status: 'Pendente',
    priority: 'Alta',
    responsible: 'Ana Paula',
    category: 'Auditoria',
    description: 'Necessário ajustar dados cadastrais.',
  },
  {
    client: 'Empresa A',
    callReason: 'Atualização de dados',
    status: 'Aberto',
    priority: 'Alta',
    responsible: 'Maria Souza',
    category: 'Auditoria',
    description: 'Solicitação de suporte técnico urgente.',
  },
] as const;
