/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * onec
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type CreateCredential201 = typeof CreateCredential201[keyof typeof CreateCredential201] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateCredential201 = {
  null: 'null',
} as const;
