/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * onec
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type CreatePartner201 = typeof CreatePartner201[keyof typeof CreatePartner201] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreatePartner201 = {
  null: 'null',
} as const;
