/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * onec
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type CreateClient201 = typeof CreateClient201[keyof typeof CreateClient201] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateClient201 = {
  null: 'null',
} as const;
