/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * onec
 * OpenAPI spec version: 1.0.0
 */

export type CreateClientBody = {
  /** @nullable */
  enterprise: string | null;
  /** @nullable */
  competenceMonth: string | null;
  /** @nullable */
  cnpj: string | null;
  /** @nullable */
  contestation: string | null;
  /** @nullable */
  returned: string | null;
  /** @nullable */
  product: string | null;
};
