/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * onec
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type CreateClientReceipt201 = typeof CreateClientReceipt201[keyof typeof CreateClientReceipt201] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateClientReceipt201 = {
  null: 'null',
} as const;
