/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * onec
 * OpenAPI spec version: 1.0.0
 */

export type CreateCredentialBody = {
  /** @nullable */
  channelHead: string | null;
  /** @nullable */
  cnpj: string | null;
  /** @nullable */
  agentIndicator: string | null;
  /** @nullable */
  partner: string | null;
};
