/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * onec
 * OpenAPI spec version: 1.0.0
 */
import type { CreatePendingBodyStatus } from './createPendingBodyStatus';
import type { CreatePendingBodyCategory } from './createPendingBodyCategory';

export type CreatePendingBody = {
  /** @nullable */
  client: string | null;
  /** @nullable */
  callReason: string | null;
  /** @nullable */
  status: CreatePendingBodyStatus;
  /** @nullable */
  priority: string | null;
  /** @nullable */
  responsible: string | null;
  category: CreatePendingBodyCategory;
  /** @nullable */
  description: string | null;
};
