/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * onec
 * OpenAPI spec version: 1.0.0
 */

export type CreatePendingBodyCategory = typeof CreatePendingBodyCategory[keyof typeof CreatePendingBodyCategory];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreatePendingBodyCategory = {
  SAC: 'SAC',
  Atendimento: 'Atendimento',
  Financeiro: 'Financeiro',
  Diretoria: 'Diretoria',
  Comercial: 'Comercial',
  Auditoria: 'Auditoria',
} as const;
