/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * onec
 * OpenAPI spec version: 1.0.0
 */

export type CreateDataNegotiationBody = {
  /** @nullable */
  title: string | null;
  /** @nullable */
  client: string | null;
  /** @nullable */
  user: string | null;
  /** @nullable */
  tags: string | null;
  /** @nullable */
  step: string | null;
  /** @nullable */
  status: string | null;
  /** @nullable */
  value: number | null;
  /** @nullable */
  partnerId: string | null;
  /** @nullable */
  startsDate: string | null;
  /** @nullable */
  observation: string | null;
  /** @nullable */
  averageGuide: number | null;
};
