/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * onec
 * OpenAPI spec version: 1.0.0
 */
import type { GetOnePending200Status } from './getOnePending200Status';
import type { GetOnePending200Category } from './getOnePending200Category';

export type GetOnePending200 = {
  id: string;
  /** @nullable */
  client: string | null;
  /** @nullable */
  callReason: string | null;
  /** @nullable */
  status: GetOnePending200Status;
  /** @nullable */
  priority: string | null;
  /** @nullable */
  responsible: string | null;
  /** @nullable */
  category: GetOnePending200Category;
  /** @nullable */
  description: string | null;
  createdAt?: string;
  updatedAt?: string;
};
