/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * onec
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type GetPendings200ItemCategory = typeof GetPendings200ItemCategory[keyof typeof GetPendings200ItemCategory] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetPendings200ItemCategory = {
  SAC: 'SAC',
  Atendimento: 'Atendimento',
  Financeiro: 'Financeiro',
  Diretoria: 'Diretoria',
  Comercial: 'Comercial',
  Auditoria: 'Auditoria',
} as const;
