/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * onec
 * OpenAPI spec version: 1.0.0
 */
import type { GetPendings200ItemStatus } from './getPendings200ItemStatus';
import type { GetPendings200ItemCategory } from './getPendings200ItemCategory';

export type GetPendings200Item = {
  id: string;
  /** @nullable */
  client: string | null;
  /** @nullable */
  callReason: string | null;
  /** @nullable */
  status: GetPendings200ItemStatus;
  /** @nullable */
  priority: string | null;
  /** @nullable */
  responsible: string | null;
  /** @nullable */
  category: GetPendings200ItemCategory;
  /** @nullable */
  description: string | null;
  createdAt?: string;
  updatedAt?: string;
};
