/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * onec
 * OpenAPI spec version: 1.0.0
 */

export type GetPortalControllsBySelectParternRoute200Item = {
  /** @nullable */
  id: string | null;
  /** @nullable */
  monthOfCalculation: string | null;
  /** @nullable */
  competenceMonth: string | null;
  /** @nullable */
  contract: number | null;
  /** @nullable */
  enterprise: string | null;
  /** @nullable */
  product: string | null;
  /** @nullable */
  percentageHonorary: number | null;
  /** @nullable */
  compensation: number | null;
  /** @nullable */
  honorary: number | null;
  /** @nullable */
  tax: number | null;
  /** @nullable */
  tj: number | null;
  /** @nullable */
  value: number | null;
  /** @nullable */
  situation: string | null;
  partnerId: string;
};
