/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * onec
 * OpenAPI spec version: 1.0.0
 */

export type ListCredentialClient200ItemClients = {
  [x: string]: any;
  id: string;
  enterprise: string;
  competenceMonth: string;
  cnpj: string;
  contestation: string;
  returned: string;
};
