/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * onec
 * OpenAPI spec version: 1.0.0
 */

export type UpdateUserBody = {
  email?: string;
  /** @minLength 6 */
  password?: string;
  role?: string;
};
