/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * onec
 * OpenAPI spec version: 1.0.0
 */

export type UpdateClientReceiptBody = {
  /** @nullable */
  receiptDate?: string | null;
  /** @nullable */
  competence?: string | null;
  /** @nullable */
  cnpj?: string | null;
  /** @nullable */
  clientName?: string | null;
  /** @nullable */
  percentage?: number | null;
  /** @nullable */
  compensationMonth?: string | null;
  /** @nullable */
  honorary?: number | null;
  /** @nullable */
  tax?: number | null;
  /** @nullable */
  status?: string | null;
};
