/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * onec
 * OpenAPI spec version: 1.0.0
 */
import type { UpdatePendingBodyStatus } from './updatePendingBodyStatus';
import type { UpdatePendingBodyCategory } from './updatePendingBodyCategory';

export type UpdatePendingBody = {
  /** @nullable */
  client?: string | null;
  /** @nullable */
  callReason?: string | null;
  /** @nullable */
  status?: UpdatePendingBodyStatus;
  /** @nullable */
  priority?: string | null;
  /** @nullable */
  responsible?: string | null;
  /** @nullable */
  category?: UpdatePendingBodyCategory;
  /** @nullable */
  description?: string | null;
};
