/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * onec
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type UpdatePendingBodyStatus = typeof UpdatePendingBodyStatus[keyof typeof UpdatePendingBodyStatus] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdatePendingBodyStatus = {
  Aberto: 'Aberto',
  Encaminhado: 'Encaminhado',
  Pendente: 'Pendente',
  Concluído: 'Concluído',
} as const;
