/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * onec
 * OpenAPI spec version: 1.0.0
 */

export type UpdateNegotiationBody = {
  title?: string;
  client?: string;
  user?: string;
  tags?: string;
  step?: string;
  status?: string;
  value?: number;
  /** @nullable */
  startsDate?: string | null;
  /** @nullable */
  partnerId?: string | null;
  /** @nullable */
  observation?: string | null;
  /** @nullable */
  averageGuide?: number | null;
};
