export const partners = [
  {
    nome: 'Santos das Neves - EI',
    'cpf/cnpj': '03.942.587/0001-46',
    cidade: 'Nogueira das Flores',
    estado: 'PE',
    comissao: '9%',
    portal_login: 'theoda-luz',
    head_canal: 'Bruno Farias',
    regional: 'Dias de da Paz',
    coordenador: 'João Guilherme Teixeira',
    agente: 'Bruna Moreira',
    indicador: 'Emilly Moreira',
    contrato: '#3888',
    telefone: '(021) 1616 1365',
    email: 'fernando23@novaes.org',
    responsavel: 'Mariana da Rosa',
  },
  {
    nome: 'Rodrigues Viana S/A',
    'cpf/cnpj': '67.432.851/0001-84',
    cidade: 'da Mota Verde',
    estado: 'MS',
    comissao: '12%',
    portal_login: 'julianapinto',
    head_canal: 'Davi Lucas Silveira',
    regional: 'Ferreira da Serra',
    coordenador: 'Benjamin Sales',
    agente: 'Maria Costela',
    indicador: 'Luigi Ramos',
    contrato: '#8911',
    telefone: '+55 (084) 6214 9306',
    email: 'julia41@castro.net',
    responsavel: 'Erick Pinto',
  },
  {
    nome: 'da Mota',
    'cpf/cnpj': '74.510.832/0001-94',
    cidade: 'Rezende',
    estado: 'GO',
    comissao: '18%',
    portal_login: 'joaoalmeida',
    head_canal: 'Enzo Moraes',
    regional: 'Moreira Grande',
    coordenador: 'Maitê da Mota',
    agente: 'Leonardo Porto',
    indicador: 'Gustavo Henrique Aragão',
    contrato: '#8171',
    telefone: '81 0093 8788',
    email: 'joao-gabriel33@jesus.net',
    responsavel: 'Kaique Ramos',
  },
  {
    nome: 'Fogaça Nascimento S/A',
    'cpf/cnpj': '90.316.874/0001-45',
    cidade: 'Farias das Pedras',
    estado: 'CE',
    comissao: '4%',
    portal_login: 'vitor-gabriel32',
    head_canal: 'Ana Julia da Cruz',
    regional: 'Vieira do Oeste',
    coordenador: 'Cecília Dias',
    agente: 'Ana Luiza Rodrigues',
    indicador: 'Diego Viana',
    contrato: '#7857',
    telefone: '(061) 1856 9226',
    email: 'thiagosilva@viana.org',
    responsavel: 'Bruna Costa',
  },
  {
    nome: 'Nogueira',
    'cpf/cnpj': '01.378.956/0001-94',
    cidade: 'da Cruz',
    estado: 'ES',
    comissao: '9%',
    portal_login: 'kevincarvalho',
    head_canal: 'Paulo Correia',
    regional: 'Porto do Amparo',
    coordenador: 'Miguel Azevedo',
    agente: 'Lorena da Mota',
    indicador: 'Raquel da Costa',
    contrato: '#4650',
    telefone: '61 9055-1220',
    email: 'da-luznicole@da.com',
    responsavel: 'Isis Gomes',
  },
  {
    nome: 'Novaes',
    'cpf/cnpj': '41.786.259/0001-97',
    cidade: 'Teixeira',
    estado: 'RS',
    comissao: '9%',
    portal_login: 'acosta',
    head_canal: 'Ana Luiza Caldeira',
    regional: 'Oliveira da Mata',
    coordenador: 'Davi Luiz Almeida',
    agente: 'João Guilherme Teixeira',
    indicador: 'Juan Moura',
    contrato: '#2906',
    telefone: '+55 11 6830-5388',
    email: 'zmoura@da.com',
    responsavel: 'Sra. Valentina Caldeira',
  },
  {
    nome: 'Ribeiro',
    'cpf/cnpj': '37.548.219/0001-30',
    cidade: 'Aragão',
    estado: 'RR',
    comissao: '3%',
    portal_login: 'milena26',
    head_canal: 'Nicolas Nunes',
    regional: 'da Cruz',
    coordenador: 'Benjamin das Neves',
    agente: 'Yuri Souza',
    indicador: 'Dr. Joaquim Gomes',
    contrato: '#6735',
    telefone: '+55 41 3999-8656',
    email: 'dmoraes@da.com',
    responsavel: 'Larissa Pereira',
  },
  {
    nome: 'Mendes',
    'cpf/cnpj': '16.825.749/0001-08',
    cidade: 'da Cruz do Norte',
    estado: 'MS',
    comissao: '15%',
    portal_login: 'helenada-costa',
    head_canal: 'Melissa Viana',
    regional: 'Carvalho da Praia',
    coordenador: 'Diogo Moreira',
    agente: 'Juan da Costa',
    indicador: 'Bruna Rodrigues',
    contrato: '#1168',
    telefone: '+55 51 3016 0496',
    email: 'peixotoluiz-fernando@farias.com',
    responsavel: 'Sr. João Miguel Ferreira',
  },
  {
    nome: 'Mendes',
    'cpf/cnpj': '81.476.320/0001-14',
    cidade: 'Pinto do Sul',
    estado: 'PB',
    comissao: '6%',
    portal_login: 'maria-alicemelo',
    head_canal: 'Caroline Viana',
    regional: 'Duarte do Norte',
    coordenador: 'Vitor Hugo Moreira',
    agente: 'Dr. Nathan Lopes',
    indicador: 'Srta. Lívia Mendes',
    contrato: '#4743',
    telefone: '61 2855 0567',
    email: 'silvalaura@rezende.net',
    responsavel: 'Gustavo Henrique da Luz',
  },
  {
    nome: 'Cavalcanti',
    'cpf/cnpj': '63.754.901/0001-99',
    cidade: 'Rocha Grande',
    estado: 'RN',
    comissao: '15%',
    portal_login: 'pedro-miguelcarvalho',
    head_canal: 'Benício Costela',
    regional: 'Nascimento do Oeste',
    coordenador: 'Júlia da Paz',
    agente: 'Ana Melo',
    indicador: 'Sra. Milena Novaes',
    contrato: '#8247',
    telefone: '0800-773-1708',
    email: 'ana98@alves.org',
    responsavel: 'Dra. Mariane Nascimento',
  },
  {
    nome: 'da Cruz S/A',
    'cpf/cnpj': '32.947.560/0001-44',
    cidade: 'Lima Paulista',
    estado: 'GO',
    comissao: '13%',
    portal_login: 'ucosta',
    head_canal: 'Sra. Júlia Caldeira',
    regional: 'Melo de da Paz',
    coordenador: 'João Felipe Caldeira',
    agente: 'Laura Cardoso',
    indicador: 'Alice Nunes',
    contrato: '#1545',
    telefone: '0500 903 8733',
    email: 'melodavi-luiz@costa.br',
    responsavel: 'Maria Clara Jesus',
  },
  {
    nome: 'Peixoto',
    'cpf/cnpj': '74.215.968/0001-71',
    cidade: 'Caldeira Verde',
    estado: 'DF',
    comissao: '6%',
    portal_login: 'laracavalcanti',
    head_canal: 'Bárbara Silva',
    regional: 'Santos do Campo',
    coordenador: 'Ana Lívia Cavalcanti',
    agente: 'Gabriel Nogueira',
    indicador: 'Luana Freitas',
    contrato: '#9047',
    telefone: '0800 812 8409',
    email: 'rezendebrenda@freitas.br',
    responsavel: 'Lucca Moraes',
  },
  {
    nome: 'Nascimento',
    'cpf/cnpj': '38.957.642/0001-56',
    cidade: 'Castro',
    estado: 'AL',
    comissao: '19%',
    portal_login: 'vmonteiro',
    head_canal: 'Yuri Cardoso',
    regional: 'da Cunha de Goiás',
    coordenador: 'Diogo Barbosa',
    agente: 'Lucas Gabriel Correia',
    indicador: 'Lucas Gabriel Teixeira',
    contrato: '#4180',
    telefone: '+55 84 3656-1255',
    email: 'hteixeira@ferreira.br',
    responsavel: 'Alexandre Peixoto',
  },
  {
    nome: 'Barros',
    'cpf/cnpj': '87.062.941/0001-38',
    cidade: 'da Mota de da Paz',
    estado: 'PE',
    comissao: '2%',
    portal_login: 'stephany52',
    head_canal: 'Ana Laura Monteiro',
    regional: 'da Cruz Alegre',
    coordenador: 'Bernardo da Conceição',
    agente: 'Carlos Eduardo Cardoso',
    indicador: 'Diogo Moreira',
    contrato: '#5039',
    telefone: '+55 (081) 6882 2656',
    email: 'pcardoso@ramos.com',
    responsavel: 'Emilly Novaes',
  },
  {
    nome: 'Castro - ME',
    'cpf/cnpj': '84.236.701/0001-14',
    cidade: 'das Neves',
    estado: 'MT',
    comissao: '7%',
    portal_login: 'souzajoana',
    head_canal: 'João Miguel Azevedo',
    regional: 'Rezende',
    coordenador: 'Dra. Eduarda Azevedo',
    agente: 'Natália Santos',
    indicador: 'Henrique Carvalho',
    contrato: '#3463',
    telefone: '+55 11 0370-8951',
    email: 'fmoura@teixeira.net',
    responsavel: 'Dr. Bruno das Neves',
  },
  {
    nome: 'Cavalcanti',
    'cpf/cnpj': '18.326.954/0001-54',
    cidade: 'da Luz',
    estado: 'MS',
    comissao: '8%',
    portal_login: 'alexiasantos',
    head_canal: 'Vinicius Freitas',
    regional: 'Novaes de da Costa',
    coordenador: 'Júlia Mendes',
    agente: 'Melissa Jesus',
    indicador: 'Sarah Duarte',
    contrato: '#3687',
    telefone: '81 0267 1603',
    email: 'jsales@cavalcanti.org',
    responsavel: 'Gabrielly Nogueira',
  },
  {
    nome: 'Costela S/A',
    'cpf/cnpj': '87.315.604/0001-05',
    cidade: 'Rodrigues',
    estado: 'RO',
    comissao: '12%',
    portal_login: 'souzamanuela',
    head_canal: 'Nicolas Correia',
    regional: 'Moreira',
    coordenador: 'Mirella Rodrigues',
    agente: 'Luigi Nascimento',
    indicador: 'Agatha Moura',
    contrato: '#3076',
    telefone: '+55 81 1228-4016',
    email: 'amoraes@silveira.br',
    responsavel: 'Leandro Nunes',
  },
  {
    nome: 'Fogaça Barbosa S.A.',
    'cpf/cnpj': '40.826.179/0001-55',
    cidade: 'Vieira',
    estado: 'SP',
    comissao: '6%',
    portal_login: 'thales62',
    head_canal: 'Bruna Fogaça',
    regional: 'da Mota',
    coordenador: 'Marcelo Fogaça',
    agente: 'Guilherme Lima',
    indicador: 'Fernando Peixoto',
    contrato: '#1897',
    telefone: '+55 61 5926 9062',
    email: 'ana-laura63@da.org',
    responsavel: 'Sr. Otávio da Luz',
  },
] as const;
