/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AuthLayoutRouteImport } from './pages/_auth/layout'
import { Route as AppLayoutRouteImport } from './pages/_app/layout'
import { Route as AuthSignInRouteImport } from './pages/_auth/sign-in'
import { Route as AppBusinessDashboardIndexRouteImport } from './pages/_app/_business-dashboard/index'
import { Route as AppBusinessDashboardDashboardLayoutRouteImport } from './pages/_app/_business-dashboard/dashboard/layout'
import { Route as AppBusinessDashboardDashboardIndexRouteImport } from './pages/_app/_business-dashboard/dashboard/index'

const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AppBusinessDashboardIndexRoute =
  AppBusinessDashboardIndexRouteImport.update({
    id: '/_business-dashboard/',
    path: '/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppBusinessDashboardDashboardLayoutRoute =
  AppBusinessDashboardDashboardLayoutRouteImport.update({
    id: '/_business-dashboard/dashboard',
    path: '/dashboard',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppBusinessDashboardDashboardIndexRoute =
  AppBusinessDashboardDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppBusinessDashboardDashboardLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/sign-in': typeof AuthSignInRoute
  '/dashboard': typeof AppBusinessDashboardDashboardLayoutRouteWithChildren
  '/': typeof AppBusinessDashboardIndexRoute
  '/dashboard/': typeof AppBusinessDashboardDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof AuthSignInRoute
  '/': typeof AppBusinessDashboardIndexRoute
  '/dashboard': typeof AppBusinessDashboardDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppLayoutRouteWithChildren
  '/_auth': typeof AuthLayoutRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_app/_business-dashboard/dashboard': typeof AppBusinessDashboardDashboardLayoutRouteWithChildren
  '/_app/_business-dashboard/': typeof AppBusinessDashboardIndexRoute
  '/_app/_business-dashboard/dashboard/': typeof AppBusinessDashboardDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/sign-in' | '/dashboard' | '/' | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to: '/sign-in' | '/' | '/dashboard'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_auth/sign-in'
    | '/_app/_business-dashboard/dashboard'
    | '/_app/_business-dashboard/'
    | '/_app/_business-dashboard/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_app/_business-dashboard/': {
      id: '/_app/_business-dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppBusinessDashboardIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_business-dashboard/dashboard': {
      id: '/_app/_business-dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppBusinessDashboardDashboardLayoutRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_business-dashboard/dashboard/': {
      id: '/_app/_business-dashboard/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppBusinessDashboardDashboardIndexRouteImport
      parentRoute: typeof AppBusinessDashboardDashboardLayoutRoute
    }
  }
}

interface AppBusinessDashboardDashboardLayoutRouteChildren {
  AppBusinessDashboardDashboardIndexRoute: typeof AppBusinessDashboardDashboardIndexRoute
}

const AppBusinessDashboardDashboardLayoutRouteChildren: AppBusinessDashboardDashboardLayoutRouteChildren =
  {
    AppBusinessDashboardDashboardIndexRoute:
      AppBusinessDashboardDashboardIndexRoute,
  }

const AppBusinessDashboardDashboardLayoutRouteWithChildren =
  AppBusinessDashboardDashboardLayoutRoute._addFileChildren(
    AppBusinessDashboardDashboardLayoutRouteChildren,
  )

interface AppLayoutRouteChildren {
  AppBusinessDashboardDashboardLayoutRoute: typeof AppBusinessDashboardDashboardLayoutRouteWithChildren
  AppBusinessDashboardIndexRoute: typeof AppBusinessDashboardIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppBusinessDashboardDashboardLayoutRoute:
    AppBusinessDashboardDashboardLayoutRouteWithChildren,
  AppBusinessDashboardIndexRoute: AppBusinessDashboardIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
