import type { GetContractNegotiationSummary200 } from '../../generated/types/GetContractNegotiationSummary';

type SummaryItem = GetContractNegotiationSummary200['result'][number];

export const fieldLabels: Record<keyof SummaryItem, string> = {
  negotiationId: 'Id da negociação',
  title: 'Título',
  negotiationClient: 'Cliente da negociação',
  user: 'Usuário',
  tags: 'tags',
  step: 'Etapa',
  negotiationStatus: 'Status da negociação',
  value: 'Valor',
  startsDate: 'Data de Início',
  observation: 'OBS',
  partnerId: 'Parceiro',
  negotiationAverageGuide: 'Guia de Média da Negociação',
  negotiationCreatedAt: 'Negociação Criada em',
  negotiationUpdatedAt: 'Negociação Atualizada em',
  contractId: 'Id do contrato',
  contractClient: 'Cliente do Contrato',
  city: 'Cidade',
  state: 'Estado',
  cnpj: 'CNPJ',
  sindic: 'Síndico',
  year: 'Ano',
  matter: 'Matéria',
  forecast: 'Previsão',
  contractTotal: 'Total do valor do contrato',
  percentage: 'Percentual',
  signedContract: 'Contrato Assinado',
  contractStatus: 'Status do contrato',
  contractAverageGuide: 'Guia de Média do Contrato',
  partner: 'Parceiro',
  partnerCommission: 'Commisão do Parceiro',
  counter: 'Contador',
  email: 'E-mail do responsável',
  contractCreatedAt: '',
  contractUpdatedAt: '',
};
